apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-deployment
  namespace: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      serviceAccount: pyapp-sa
      containers:
        - name: pyapp
          image: us-central1-docker.pkg.dev/searce-playground-v2/alisha-test-repo:v1
          ports: 
            - containerPort: 8080
